services:

  wa-gateway:
    build: ./wa-gateway
    container_name: wa-gateway-veritapp
    networks:
      - n8n-veritapp
    restart:
      unless-stopped
    environment:
      - VERIFY_TOKEN=veritapp_2025
      - APP_SECRET=4ada0e086e8c89ed92119b8ca453216d
      - N8N_WEBHOOK_URL=http://n8n-webhooks:5678/webhook/veritapp_queue
    ports:
      - "3010:3000"
    depends_on:
      - n8n-webhooks

  n8n-editor:
    image: n8nio/n8n:latest
    container_name: n8n-editor-veritapp
    ports:
      - 5678:5678
    networks:
      - n8n-veritapp
    restart:
      unless-stopped
    volumes:
      - ./n8n-data:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env

  n8n-workers:
    image: n8nio/n8n:latest
    networks:
      - n8n-veritapp
    restart:
      unless-stopped
    volumes:
      - ./n8n-data:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    command: worker
    deploy:
      replicas: 2
    environment:
      - N8N_WORKER_CONCURRENCY=10


  n8n-webhooks:
    image: n8nio/n8n:latest
    container_name: n8n-webhooks-veritapp
    ports:
      - 5677:5678
    networks:
      - n8n-veritapp
    restart:
      unless-stopped
    volumes:
      - ./n8n-data:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    command: webhook


  postgres:
    image: ankane/pgvector
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: n8n
      POSTGRES_USER: postgres
    networks:
      - n8n-veritapp
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_Veritapp -d n8n"]
      interval: 10s
      timeout: 5s
      retries: 10


  redis:
    image: redis:7
    ports:
      - 6379:6379
    networks:
      - n8n-veritapp
    restart:
      always
    volumes:
      - ./redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 5s
      retries: 10


networks:
  n8n-veritapp:
    driver: bridge
